name = "Bun Starter"
id = "bun-starter"
icon = "https://bun.sh/logo.svg"
description = "Deploy an Bun Starter easily!"
tags = ["bun", "starter"]

[source]
image = "ghcr.io/opraying/bun-starter:latest"
command = ["bun", "start"]

[[ports]]
id = "web"
port = 3000
type = "HTTP"

[env]
PORT = { default = 3000 }