name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-

    - name: Use Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Lint
      run: bun run lint

    - name: Type check
      run: bun run typecheck

    - name: Build
      run: bun run build

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
        file: ./Dockerfile

    - name: Delete old latest image
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const packageName = repo.toLowerCase();

          core.info('Fetching package versions...');
          try {
            const { data: versions } = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
              package_type: 'container',
              package_name: packageName,
              org: owner
            });

            core.info('API Response:');
            console.log(JSON.stringify(versions, null, 2));

            const latestVersion = versions.find(v => v.metadata.container.tags.includes('latest'));

            if (!latestVersion) {
              core.info('No old latest image found to delete');
              return;
            }

            core.info(`Deleting old latest image with ID: ${latestVersion.id}`);

            await github.rest.packages.deletePackageVersionForOrg({
              package_type: 'container',
              package_name: packageName,
              org: owner,
              package_version_id: latestVersion.id
            });

            core.info('Successfully deleted old latest image');
          } catch (error) {
            core.setFailed(`Error: ${error.message}`);
          }